config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations"
  }, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
  }

  root to: 'tweets#index'
  resources :users, only: [:show, :edit, :update] do
    resource :follow
    resources :followings
    resources :followers
  end

  resources :tweets do
    resource :likes, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :events do
    resources :registrations, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :post, presence: true, length: { maximum: 600 }

  has_many :answers, dependent: :destroy
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @questions = Question.all.order('created_at DESC')
  end

  def show
    @answer = Answer.new
    @answers = @question.answers.includes(:user)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path, notice: '質問の投稿が完了しました'
    else
      flash.now[:alert] = '質問の投稿できませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question), notice: '質問を編集しました'
    else
      flash.now[:alert] = '質問を編集できませんでした'
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: '質問を削除しました'
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user.id == @question.user_id
  end

  def question_params
    params.require(:question).permit(:title, :post).merge(user_id: current_user.id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<div class="question-wrapper">
  <div class="question-container">
    <h1>質問を編集<h1>
  <div class="question-border">  
    <%=form_with model:@question, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="question-title">
        <p><%= f.label :"タイトル" %></p>
        <%= f.text_field :title, placeholder: "100文字以内でご入力ください", maxlength: "100" %>
      </div>
      <div class="question-text">
        <p><%= f.label :"質問内容"%></p>
        <%= f.text_area :post, placeholder: "600文字以内でご入力ください", maxlength: "600" %>
      </div>
    </div>
      <div class="submit-question">
        <%= f.submit "編集する", class:"submit-tweet" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="question-index-wrapper">
  <div class="question-index-container">
  <h1>ランナー知恵袋</h1>
  <%= link_to new_question_path, class:"under-line" do %>
        <i class="fas fa-question"></i> <span>質問する</span>
      <% end %>
   <% @questions.each do |question| %>
    <div class="question-contents">
      <div class="title-katamari">
        <div class="question-index-title">
          <p>タイトル</p>
          <div class="name-of-title">
            <%= link_to question.title, question_path(question),class:"under-line" %>
          </div>
        </div>
      </div>
      <div class="title-katamari">
        <div class="question-index-title">
          <p>投稿者</p>
          <div class="question-index-nickname">
            <%= link_to question.user.nickname, user_path(question.user.id), class:"under-line" %>
          </div>
        </div>
      </div>
      <div class="title-katamari">
        <div class="question-index-title">
          <p>投稿日時</p>
          <div class="question-index-createdate">
            <%= question.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          </div>
        </div>
      </div>
    </div>
   <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="question-wrapper">
  <div class="question-container">
    <h1>質問する<h1>
  <div class="question-border">  
    <%=form_with model:@question,local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="question-title">
        <p><%= f.label :"タイトル" %></p>
        <%= f.text_field :title, placeholder: "100文字以内でご入力ください", maxlength: "100" %>
      </div>
      <div class="question-text">
        <p><%= f.label :"質問内容"%></p>
        <%= f.text_area :post, placeholder: "600文字以内でご入力ください", maxlength: "600" %>
      </div>
    </div>
      <div class="submit-question">
        <%= f.submit "質問する", class:"submit-tweet" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="question-show-wrapper">
  <div class="question-show-container">
    <div class="question-title">
      <div class="q-title">
        <%= @question.title %>
      </div>
      <div class="q-create-date">
       <div class="q-person">投稿者 <%= @question.user.nickname %></div>
       <div>投稿日時 <%= @question.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
       </div>
       <%= link_to "知恵袋トップへ", questions_path, class:"under-line"%>
      </div>
    </div>
     <p class="question-content"><%= @question.post %></p>
    <span>
    <% if current_user.id == @question.user_id %>
      <%= link_to question_path(@question), method: :delete, data: {
            confirm: '本当に削除して良いですか?',
            cencel: 'やめる',
            commit: '削除する'}, title: '削除確認', class: "under-line"  do %>
        <i class="fas fa-trash-alt"></i>
    <% end %>  
      <%= link_to edit_question_path(@question), method: :get, class:"under-line" do %>
        <i class="fas fa-edit"></i>
      <% end %>
    <% end %>  
    </span>
    <%# 回答エリア %>
    <div class="answer-container">
      <%= form_with(model: [@question, @answer], local: true) do |f| %>
        <%= f.text_area :message, placeholder: "回答する(500文字以内)" , class: "answer-area"%> 
        <%= f.submit "Reply", class:"reply-answer" %>
      <% end %>   
      <div id="answers">
      <b>回答一覧</b>
        <% @answers.each do |answer| %> 
        <%if @question.user_id == answer.user_id %>
         <p class="answer-people">
         <% if answer.user.image.attached? %>
          <span><%= image_tag answer.user.image.variant(resize: '80x80'), class:"user-pic answer-pic",id: "img" %></span>
         <% end %>  
          <%= link_to answer.user.nickname, user_path(answer.user.id), class:"under-line answer-name" %>
          <p class="real-person">(投稿者本人)<p>
          <p>
          <div class="answer-date">
            <%= answer.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          </div>
          <div class="question-answer-content">
          <strong><%= answer.message %></strong>   
          <span>
            <% if current_user.id == answer.user_id %>
              <%=link_to question_answer_path(@question, @question.answers.ids), method: :delete do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </span>
        </div> 
        <% else %>
          <p class="answer-people">
          <% if answer.user.image.attached? %>
            <span><%= image_tag answer.user.image.variant(resize: '80x80'), class:"user-pic answer-pic",id: "img" %></span>
          <% end %>  
          <%= link_to answer.user.nickname, user_path(answer.user.id), class:"under-line answer-name"%>
          <p>
          <div class="answer-date">
            <%= answer.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          </div>
          <div class="answer-content">
          <strong><%= answer.message %></strong>   
          <span>
            <% if current_user.id == answer.user_id %>
              <%=link_to question_answer_path(@question, @question.answers.ids), method: :delete do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </span>
        </div>
        <% end %>
      <% end %>
      <div>
    </div>
  </div>
</div>