config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations"
  }, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
  }

  root to: 'tweets#index'
  resources :users, only: [:show, :edit, :update] do
    resource :follow
    resources :followings
    resources :followers
  end

  resources :tweets do
    resource :likes, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :events do
    resources :registrations, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images

  validates :text, presence: true # unless: :was_attached?

  # def was_attached?
  #   self.images.attached?
  # end

  def self.search(search)
    if search != ''
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_tweet, only: [:edit, :update, :show, :destroy]
  before_action :prohibit_access, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.includes(:user).order('created_at DESC')
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path, notice: '投稿が完了しました'
    else
      flash.now[:alert] = '投稿ができませんでした'
      render :new
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path, notice: '投稿を削除しました'
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to root_path, notice: '投稿を編集しました'
    else
      flash.now[:alert] = '投稿の編集ができませんでした'
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def prohibit_access
    redirect_to root_path unless current_user.id == @tweet.user_id
  end

  def tweet_params
    params.require(:tweet).permit(:text, images: []).merge(user_id: current_user.id)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
  <div class="tweet-container">
    <% if current_user.image.attached?%>
      <span><%= image_tag current_user.image.variant(resize: '90x90'), class:"user-pic" %>さん、こんにちは</span>
    <% else %>
      <p class="tweet-user-nickname" ><% current_user.nickname %></p>
    <% end %>
      <%= form_with model: @tweet, url: tweet_path(@tweet), local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

       <%= f.text_area :text, class:"text-post", rows: "10", maxlength: "140" %>
        <div class="tweet-image">
         <label>
            <%= f.label :image, id: "images", class: "far fa-images fa-2x" do %>
              <%= f.file_field :images, name: 'tweet[images][]', id: "tweet_image", style:"display:none;" %>
            <% end %>
          </label>
        </div>
        <div>
          <%= f.submit "Edit", class:"submit-tweet" %>
        </div>
      
    <% end %>

app/views/tweets/index.html.erb
  <div class="article">
    <div class="side">
      <%= form_with(url: search_tweets_path, local: true, method: :get,  class: "search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= f.submit "検索", class: "search-btn" %>
      <% end %>
      <ul class="menu-contents">
       <li class="content">
        <%=link_to events_path,class:"under-line" do %>
          <i class="fas fa-calendar-week"><span>大会・イベント</span></i>
        <% end %>
        </li>
       <li class="content">
        <%= link_to questions_path, class:"under-line" do %>
          <i class="fas fa-question"><span>ランナー知恵袋</span></i>
        <% end %>
        </li>
        <li class="content">
        <%= link_to rooms_path, class:"under-line" do %>
          <i class="far fa-comments"><span>チャットルーム</span></i>
        <% end %>
        </li>
        <li class="tweet-btn">
          <%= link_to new_tweet_path, class:"under-line" do%>
            <span>Tweetする</span>
            <% end %>
        </li>
      </ul>
    </div>

    <div class="contents row">
      <% @tweets.each do |tweet| %>
        <div class="tweets">
          <div class="nickname">
          <% if tweet.user.image.attached?  %>
            <span><%= image_tag tweet.user.image.variant(resize: '80x80'), class:"user-pic" %></span>
          <% end %>
          <%=link_to tweet.user.nickname, user_path(tweet.user.id), class: "under-line" %>
          </div>
          <div class="slider">
            <% tweet.images.each do |image| %>
              <span><%=image_tag image.variant(resize:"600x600").processed, class: 'images' if tweet.images.attached? %></span> 
            <% end %>  
          </div>
          <div class="text-area">
             <%= tweet.text %>
          </div>
          <div class="like-and-detail" >
            <div id="like-button-<%= tweet.id %>">
              <%= render partial: 'likes/like', locals: {tweet: tweet} %>
          </div>
            <div class="detail">
              <% if user_signed_in? %>
                <%= link_to tweet_path(tweet.id), method: :get, class:"under-line" do %>  
                <i class="far fa-comment-dots fa-2x"></i> <%= tweet.comments.count %>
              <% end %>
              
              <% end %>
            </div>
          </div>
        </div>  
      <% end %>   
    </div>   
  </div>

app/views/tweets/new.html.erb
 <div class="tweet-container">
    <% if current_user.image.attached?  %>
      <span><%= image_tag current_user.image.variant(resize: '100x100'), class:"user-pic"%>さん、どんな1日でしたか?</span>
    <% else %> 
      <p class="tweet-user-nickname"><%= current_user.nickname%>さん、どんな1日でしたか?<p>
    <% end %>
    <%= form_with model: @tweet, url: tweets_path, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.text_area :text, placeholder: "How was your day?", class:"text-post", rows: "10", maxlength:"140" %>
        <div class="tweet-image">
          <label>
            <%= f.label :image, id: "images", class: "far fa-images fa-2x" do %>
              <%= f.file_field :images, name: 'tweet[images][]', id: "tweet_image", style:"display:none;" %>
            <% end %>
          </label>
        </div>
      <div>
        <%= f.submit "Tweet", class:"submit-tweet" %>
      </div>
     <div id="image-list"></div>
    <% end %>

    <% @tweet.images.each do |image| %>
      <%= image_tag image, class: 'images' %>
    <% end %>
  </div>
  

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |f| %>
 <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
 <%= f.submit "検索", class: "search-btn" %>
<% end %>
<div class="container row">
  <% @tweets.each do |tweet| %>
    <div class="tweets">
      <% tweet.images.each do |image| %>
        <span><%= image_tag image.variant(gravity: :center, resize:"500x500^", crop:"500x500+0+0").processed, class: 'images' %></span>
      <% end %>  
    
      <p><%= tweet.text %></p>
      <span class="name">
        <%= tweet.user.nickname %>
      </span>  
      <ul class="more_list">
        <% if user_signed_in? %>
            <li>
              <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
            </li>
           <% if current_user.id == tweet.user_id %> 
            <li>
              <%= link_to "編集", edit_tweet_path(tweet.id), method: :get %>
          </li>
          <% end %>
        <% end %>
      </ul> 
    </div> 
  </div>
  <% end %> 
</div>  

app/views/tweets/show.html.erb
<div class="contents row">
  <div class="content-post" style="background-image: url(<%= @tweet.images %>);">
    <div class="tweets">
      <div class="nickname">
      <% if @tweet.user.image.attached? %>
        <span><%= image_tag @tweet.user.image.variant(resize: '90x90'), class:"user-pic" %></span>
      <% end %>   
          <%=link_to @tweet.user.nickname, user_path(@tweet.user.id), class: "under-line" %>
      </div>
      <div class="slider">
        <% @tweet.images.each do |image| %>
          <span><%= image_tag image.variant(resize:"600x600", crop:"600x600+0+0").processed, class: 'images' %></span>
        <% end %>  
      </div>
      <p><%= @tweet.text %><p>
      
      </span>
      <ul class="more-list">
        <% if current_user.id == @tweet.user_id %>
        <li>
          <%= link_to edit_tweet_path(@tweet.id), method: :get, class: "under-line" do %>
            <i class="far fa-edit fa-lg"></i>
          <% end %>
          <%= link_to tweet_path(@tweet.id), method: :delete, class: "under-line", data: {
            confirm: '本当に削除して良いですか?',
            cencel: 'やめる',
            commit: '削除する'}, title: '削除確認' do %>
            <i class="fas fa-trash-alt fa-lg"></i>
          <% end %>  
        </li>
        <% end %> 
            <p class= "under-line "><%=link_to @tweet.likes.count, tweet_likes_path(@tweet),class: "how-many-likes" %>Likes</p>
        </ul>
    </div>
  </div>
  <div class="comment-area">
    <% if user_signed_in? %>
      <%= form_with model: [@tweet, @comment], local: true do |f| %>
        <%= f.text_area :comment, class: "commentform",placeholder:"コメントする" %>
        <%= f.submit "SEND", class: "submit" %>
      <% end %>
    <% end %>
  </div>  
    <div class="comment-container" >
      <% @comments.each do |comment| %>
        <div class="balloon">
         <figure class="balloon-image-left">
          <% if comment.user.image.attached? %>
            <%= image_tag comment.user.image, id:"img" %>
          <% else %>
            <div class="comment"><%= comment.user.nickname %></div>
          <% end %>  
         <figcaption class="balloon-image-description">
          </figcaption>
          </figure>
         <div class="balloon-text-right">
           <p><%= comment.comment %>
            <% if current_user.id == comment.user_id %>
              <%= link_to tweet_comment_path(comment.tweet.id, comment.id), method: :delete, class: "under-line" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </p>  
            <% end %>
        </div>    
      <%end%> 
     </div>
  