config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations"
  }, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
  }

  root to: 'tweets#index'
  resources :users, only: [:show, :edit, :update] do
    resource :follow
    resources :followings
    resources :followers
  end

  resources :tweets do
    resource :likes, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :events do
    resources :registrations, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, on: :create
  with_options presence: true do
    validates :nickname
    validates :gender
    validates :birth_day
  end

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :questions
  has_many :answers
  has_many :events
  has_many :registrations
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_one_attached :image

  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user

  has_many :sns_credentials

  validates :full_name, format: { with: /\A[ぁ-んァ-ン一-龥々ー]+\z/, message: 'は全角(ひらがな、カタカナ、漢字)で入力してください' }

  def already_liked?(tweet)
    likes.exists?(tweet_id: tweet.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.nickname,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(_resource)
    user_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @tweets = @user.tweets
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '編集しました'
    else
      flash.now[:alert] = '編集できませんでした。'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :introduce, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
  <div class="Form">
    <div class="header-container">
      <% if @user.image.attached? %>
        <span><%=image_tag @user.image.variant(resize: '500x500'), class: "user-edit-pic" %><span>
      <% else %>
        <p class="edit-user-nickname"><%= @user.nickname %>さん</p>
      <% end %>
        <div class="profile-edit" >
          <h5>プロフィール編集</h5>
        </div>
      </div>
      <%= form_with model: @user, url: user_path(@user), local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

          <p class="Form-Item-Label"><span class="Form-Item-Label-Required fas fa-user-edit"></i></span>ニックネーム</p>
          <div class="Form-Item">
            <%= f.text_field :nickname, autofocus: true, class: "Form-Item-Input", maxlength: 10 %>
          </div>

          <p class="Form-Item-Label"><span class="Form-Item-Label-Required fas fa-user-edit"></span>プロフィール画像</p>        
          <div class="Form-Item">
            <%= f.file_field :image, class: "Form-Item-Input"%>
          </div>

          <p class="Form-Item-Label"><span class="Form-Item-Label-Required fas fa-user-edit"></span>自己紹介文</p>
          <div class="Form-Item">
            <%= f.text_area :introduce, class: "Form-Item-Input"%>     
          </div> 

          <div class="actions">
            <%= f.submit "Update", class: "Form-Btn", data: {
                    confirm: '編集してよろしいですか?',
                    cencel: 'やめる',
                    commit: '編集する'}, title: '編集確認' %>
          </div> 
        <% end %>
    </div>

app/views/users/show.html.erb
    <%# 自己紹介エリア %>
    <div class="introduce-wrapper">
      <div class="introduce-container">
        <div class="introduce-myself">
        <% if @user.image.attached? %>
          <span><%= image_tag @user.image, id:"introduce-pic" %></span>
        <% end %>  
          <p class="my-nickname"><%= @user.nickname %></p>
          <% if current_user.id == @user.id %>
           <div class="user-edit-btn">
            <%=link_to edit_user_path(@user) do%>
              <i class="edit-icon fas fa-user-edit">Edit profile</i>
            <% end %>
           </div>  
          <% else %>  
            <div class="user-edit-btn">
              <%=link_to new_room_path do%>
                <i class="edit-icon far fa-envelope">Message</i>
              <% end %>  
            </div>
          <% end %>  
          <span class="introduce-text">
            <%= @user.introduce %>
          </span>
        </div>   
      <div class="follow-function">
        <% if user_signed_in? && current_user != @user %>
          <% if current_user.active_relationships.exists?(target_user_id: @user.id ) %>
            <%= link_to 'フォローをやめる', [@user, :follow], method: :delete, class: "under-line do-following" %>
          <% else %>
            <%= link_to 'フォローする', [@user, :follow], method: :post, class: "under-line done-followed" %>
          <% end %>
        <% end %>
        <div class="follower">
          <%= @user.followings.count %>
          <%= link_to 'Following', [@user, :followings], class: "under-line" %>
          
        </div>
        <div class="follower">
          <%= @user.followers.count %>
          <%= link_to 'Followers', [@user, :followers], class: "under-line" %>
        </div>
     </div>
    </div>
  <%# 自己紹介エリア %>

  <%# ここから投稿一覧 %>
  <div class="contents row">
    <p><%= @nickname %>さんの投稿一覧</p>
      <% @tweets.each do |tweet| %>
        <div class="tweets">
          <div class="slider">
            <% tweet.images.each do |image| %>
              <span><%= image_tag image.variant(gravity: :center, resize:"600x600").processed, class: 'images' if tweet.images.attached? %></span>
            <% end %>
          </div>
          <p><%= tweet.text %></p>
        </div>
     <% end %>
  </div>