config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations"
  }, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
  }

  root to: 'tweets#index'
  resources :users, only: [:show, :edit, :update] do
    resource :follow
    resources :followings
    resources :followers
  end

  resources :tweets do
    resource :likes, only: [:show, :create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :events do
    resources :registrations, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :prefecture

  belongs_to :user
  has_many :registrations
  has_one_attached :image

  validates :fee, presence: true, numericality: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }
  validates :fee, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: 'は0円以上の金額にしてください' }
  with_options presence: true do
    validates :event_name
    validates :event_date
    validates :start_time
    validates :finish_time
    validates :place_number
    validates :place_name
    validates :deadline
    validates :description

    with_options numericality: { other_than: 1, message: 'を選択してください' } do
      validates :category_id
      validates :prefecture_id
    end
  end

  def self.search(search)
    if search != ''
      Event.where('event_name LIKE(?)', "%#{search}%")
    else
      Event.all
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :prohibit_user, only: [:edit, :update, :destroy]

  def index
    @events = Event.all.order('created_at DESC')
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event), notice: 'エントリー募集しました'
    else
      flash.now[:alert] = 'エントリー募集ができませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'エントリーを編集しました'
    else
      flash.now[:alert] = 'エントリーを編集できませんでした'
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'エントリー募集を削除しました'
  end

  def search
    @events = Event.search(params[:keyword])
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def prohibit_user
    redirect_to root_path, notice: '権限がありません' unless current_user.id == @event.user_id
  end

  def event_params
    params.require(:event).permit(:event_name, :fee, :description, :category_id,
                                  :prefecture_id, :place_number, :place_name,
                                  :event_date, :start_time, :finish_time, :deadline, :image).merge(user_id: current_user.id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="Form">
    <div class="event-subject">
      <h2>イベントを編集する<h2>
    </div>
    <%= form_with model: @event,  local: true do |f| %>

     <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>イベント名</p>
        <div class="Form-Item">
          <%= f.text_field :event_name, autofocus: true, class: "Form-Item-Input" %>
        </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:event_name) %>
          <p><%= @event.errors.full_messages_for(:event_name).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

       <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>開催日時</p>
        <div class="Form-Item">
          <%= f.date_field :event_date,class: "Form-Item-Input" %>
          </div>
          <div class="event-date">
          <%= f.time_select :start_time, minute_step: 15, class: "Form-Item-Input" %>〜<%= f.time_select :finish_time, minute_step: 15, class: "Form-Item-Input" %>
       </div>
       <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:event_date) %>
          <p><%= @event.errors.full_messages_for(:event_date).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>
      
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>カテゴリー</p>
          <div class="Form-Item">
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"Form-Item-Input", id:"event-category"}) %>
      </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:category_id) %>
          <p><%= @event.errors.full_messages_for(:category_id).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>  

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>開催地域</p>
        <div class="Form-Item">
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "Form-Item-Input", id:"event-place"}) %>
      </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:prefecture_id) %>
          <p><%= @event.errors.full_messages_for(:prefecture_id).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>開催場所(住所)</p>
          <div class="Form-Item">
          <%= f.text_field :place_number, class: "Form-Item-Input" %>
        </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:place_number) %>
          <p><%= @event.errors.full_messages_for(:place_number).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>集合場所</p>
          <div class="Form-Item">
          <%= f.text_field :place_name, placeholder: "詳しい場所の名前をご記入ください", class: "Form-Item-Input" %>
        </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:place_name) %>
          <p><%= @event.errors.full_messages_for(:place_name).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>イベントの特徴</p>
          <div class="Form-Item">
          <%= f.text_area :description, placeholder: "イベント内容を記入してください", class: "Form-Item-Textarea"%>
        </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:description) %>
          <p><%= @event.errors.full_messages_for(:description).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>エントリー期限</p>
          <div class="Form-Item">
        <%= f.date_field :deadline,class: "Form-Item-Input" %>
      </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:deadline) %>
          <p><%= @event.errors.full_messages_for(:deadline).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">任意</span>画像</p>
          <div class="Form-Item">
        <%= f.file_field :image, class: "Form-Item-Input" %>
      </div>

     <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>エントリー費</p>
          <div class="Form-Item">
          <%= f.text_field :fee, class:"Form-Item-Input", id:"entry-price", placeholder:"例）1000円(半角数字 0円以上)" %>
        </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:fee) %>
          <p><%= @event.errors.full_messages_for(:fee).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

        <p class="Form-Item-Label">エントリー手数料(10%)</p>
          <div class="Form-Item">
            <div class="Form-Item-Input" id='add-tax-fee'></div>
         </div>

        <p class="Form-Item-Label">エントリー利益(各エントリーにつき)</p>
          <div class="Form-Item">
            <span class="Form-Item-Input" id='profit'></span>
         </div>
        
      <div class="submit-btn">
        <h6>※ご記入内容にお間違いがないかもう一度ご確認ください</h6>
        <%= f.submit "募集内容を編集する", class: 'Form-Btn'%>
      </div>
    <% end %>
  </div>
</div>    

app/views/events/index.html.erb
  <div class="article">
    <div class="side">
      <%= form_with(url: search_events_path, local: true, method: :get,  class: "search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "イベントを検索する", class: "search-event-input" %>
        <%= f.submit "検索", class: "search-btn" %>
      <% end %>
      <div class="boshuusuru">
       <%=link_to new_event_path,class:"under-line" do %>
          <i class="fas fa-calendar-week"> <span>イベント or 練習会を開く</span></i>
        <% end %>
      </div>
    </div>
   <div class="contents row">
      <% @events.each do |event| %>
        <div class="tweets">
          <div class="box-title">
            <%= link_to event.event_name, event_path(event), class: "under-line" %>
          </div>
          <div class="event-index-pic">
            <%= image_tag event.image.variant(resize:"350x350^").processed, class: "images" if event.image.attached? %>
          </div>
            <ul class="event-list">
              <li>
                <b>開催日 : </b><%= event.event_date %>
              </li>
              <li>
                <b>イベントの特徴 : </b><%= event.description %>
              </li>
            </ul> 
        </div>
      <% end %> 
    </div>
  </div>

app/views/events/new.html.erb
<div class="Form">
    <div class="event-subject">
      <h2>新しいイベントを募集する<h2>
    </div>
    <%= form_with model: @event, url: events_path, local: true do |f| %>

     <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>イベント名</p>
        <div class="Form-Item">
          <%= f.text_field :event_name, autofocus: true, class: "Form-Item-Input", maxlength:"30", placeholder:"大会名など(30文字以内)" %>
        </div>
      <%# <%エラーメッセージ%>  
      <div class="event-error">
        <% if @event.errors.include?(:event_name) %>
          <p><%= @event.errors.full_messages_for(:event_name).first %></p>
        <% end %>
      </div>
      <%# <%エラーメッセージ%>

       <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>開催日時</p>
        <div class="Form-Item">
          <%= f.date_field :event_date,class: "Form-Item-Input" %>
          </div>
          <div class="event-date">
          <%= f.time_select :start_time, minute_step: 15, class: "Form-Item-Input" %>〜<%= f.time_select :finish_time, minute_step: 15, class: "Form-Item-Input" %>
       </div>
       <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:event_date) %>
            <p><%= @event.errors.full_messages_for(:event_date).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>カテゴリー</p>
          <div class="Form-Item">
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"Form-Item-Input", id:"event-category"}) %>
      </div> 
      <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:category_id) %>
            <p><%= @event.errors.full_messages_for(:category_id).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%>  

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>開催地域</p>
        <div class="Form-Item">
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "Form-Item-Input", id:"event-place"}) %>
      </div>
      <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:prefecture_id) %>
            <p><%= @event.errors.full_messages_for(:prefecture_id).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>開催場所(住所)</p>
        <div class="Form-Item">
          <%= f.text_field :place_number, class: "Form-Item-Input", placeholder: "番地まで詳しい住所を入力してください", maxlength: "140" %>
        </div>
      <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:place_number) %>
            <p><%= @event.errors.full_messages_for(:place_number).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>集合場所</p>
        <div class="Form-Item">
          <%= f.text_field :place_name, placeholder: "詳しい場所の名前をご記入ください", class: "Form-Item-Input", maxlength:"20" %>
        </div>
        <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:place_name) %>
            <p><%= @event.errors.full_messages_for(:place_name).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>イベントの特徴</p>
          <div class="Form-Item">
          <%= f.text_area :description, placeholder: "イベント内容を記入してください(300文字以内)", class: "Form-Item-Textarea", maxlength:"300" %>
        </div>
      <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:description) %>
            <p><%= @event.errors.full_messages_for(:description).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>エントリー期限</p>
          <div class="Form-Item">
        <%= f.date_field :deadline,class: "Form-Item-Input" %>
      </div>
      <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:deadline) %>
            <p><%= @event.errors.full_messages_for(:deadline).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">任意</span>画像</p>
        <div class="Form-Item">
          <%= f.file_field :image, class: "Form-Item-Input" %>
        </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>エントリー費</p>
        <div class="Form-Item">
          <%= f.text_field :fee, class:"Form-Item-Input", id:"entry-price", placeholder:"例）1000円(半角数字 0円以上)", maxlength:"5" %>
        </div>
        <%# <%エラーメッセージ%> 
        <div class="event-error">
          <% if @event.errors.include?(:fee) %>
            <p><%= @event.errors.full_messages_for(:fee).first %></p>
          <% end %>
        </div>
       <%# <%エラーメッセージ%> 

        <p class="Form-Item-Label">エントリー手数料(10%)</p>
          <div class="Form-Item">
            <div class="Form-Item-Input" id='add-tax-fee'></div>
         </div>

        <p class="Form-Item-Label">エントリー利益(各エントリーにつき)</p>
          <div class="Form-Item">
            <span class="Form-Item-Input" id='profit'></span>
         </div>
        
      <div class="submit-btn">
        <h6>※ご記入内容にお間違いがないかもう一度ご確認ください</h6>
        <%= f.submit "募集内容を投稿する", class: 'Form-Btn'%>
      </div>
    <% end %>
  </div>
</div>    

app/views/events/show.html.erb
<div class="Form">
        <div class="event-owner">
          <h2>主催 <%= @event.user.nickname %></h2>
        </div>
        <div class="event-pic">
          <%= image_tag @event.image.variant(resize:"400x400").processed if @event.image.attached? %>
        </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">イベント名</span></p>
      <div class="entry-event-name">
        <%= @event.event_name %>
      </div>  
      <div class="Form-Item">
      </div>
      

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">カテゴリー</span></p>
      <div class="entry-event-name">
        <%= @event.category.name %>
      </div>
      <div class="Form-Item">
      </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">開催日時</span></p>
        <div class="entry-event-date">
        <%= @event.event_date %>
        <%= @event.start_time.strftime('%H:%M') %>〜<%= @event.finish_time.strftime('%H:%M') %>
      </div>
      <div class="Form-Item">
      </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">開催場所</span></p>
      <div class="entry-event-name">
        <%= @event.prefecture.name %>
        <%= @event.place_number %>
      </div>
      <div class="Form-Item">
      </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">集合場所</span></p>
      <div class="entry-event-name">
        <%= @event.place_name %>
      </div>
      <div class="Form-Item">
      </div>


       <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">イベントの特徴</span></p>
      <div class="entry-event-name">
        <%= @event.description%>
        </div>
      <div class="Form-Item">
      </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">お申し込み期限</span></p>
      <div class="entry-event-name">
      <%= @event.deadline %>
      </div>
      <div class="Form-Item">
      </div>

      <p class="Form-Item-Label"><span class="Form-Item-Label-Required confirmation">エントリー料金</span></p>
       <div class="entry-total-fee">
          ¥<%= @event.fee %>
        </div>
        <div class="Form-Item"></div>

      <div class="entry-btn">
          <%= link_to event_registrations_path(@event), method: :get, class:"under-line" do%>
            <p>エントリーする<p>
            <% end %>
      </div>

      <ul class="more-list">
        <% if current_user.id == @event.user_id %>
        <li>
          <%= link_to edit_event_path(@event), method: :get, class: "under-line" do %>
          <i class="far fa-edit fa-lg"></i>
          <% end %>
          <%= link_to event_path(@event), method: :delete, class: "under-line", data: {
            confirm: '本当に削除して良いですか?',
            cencel: 'やめる',
            commit: '削除する'}, title: '削除確認' do %>
            <i class="fas fa-trash-alt fa-lg"></i>
          <% end %>  
        </li>
       <% end %> 
      </ul>   

     